#+TITLE: Org-octopress -- org-mode in octopress.
#+AUTHOR: Yoshinari Nomura (乃村 能成)
#+DATE: 2013-03-19

[[http://melpa.org/#/org-octopress][file:http://melpa.org/packages/org-octopress-badge.svg]]

* What is Org-octopress?
  Org-octopress is a package to help users those who want to write
  blog articles in org-style using [[http://octopress.org/][Octopress]] (or Jekyll).

  *Note*: This package is compatible with the org 9.0 system.

* Requirements
** Necessary packages:
   + orglue :: Add some functionality to org-mode.
               https://github.com/yoshinari-nomura/orglue
   + emacs-ctable :: Table Component for elisp
                     https://github.com/kiwanami/emacs-ctable

** Recommended packages: 
   + epic :: Evernote Picker for Cocoa Emacs (Mac user Only)
             https://github.com/yoshinari-nomura/epic

* How Org-octopress works?
** Assumed directory tree:
   : + octopress
   :   + source
   :     + blog   <- (1) You compose YYYY-MM-DD-title.org
   :     + _posts <- (2) ox-jekyll.el exports to YYYY-MM-DD-title.html (w/ YAML)
   :   + public
   :     + blog   <- (3) Jekyll exports to YYYY-MM-DD-title.html (w/o YAML).

   If you have some pictures to be included in your articles,
   I recommend you to locate them at a sub-directory of blog/.
   It'll nice to maintain the relative position with article files.

   In this work flow, YYYY-MM-DD-title.org will be also published to
   your web site. If you want to hide the original Org files, you will
   have to setup Octopress publish settings to exclude org files in
   your blog/ directory.

* Basic Settings
** Emacs Settings:
  : (require 'org-octopress)
  : (setq org-octopress-directory-top       "~/octopress/source")
  : (setq org-octopress-directory-posts     "~/octopress/source/_posts")
  : (setq org-octopress-directory-org-top   "~/octopress/source")
  : (setq org-octopress-directory-org-posts "~/octopress/source/blog")
  : (setq org-octopress-setup-file          "~/org-sty/setupfile.org")

** Octopress Settings:
   In octopress/_config.yml, you must set the permelink attribute:
   : permalink: /blog/:year-:month-:day-:title.html

* How to use
  1) M-x org-octopress
  2) Compose YYYY-MM-DD-title.org in source/blog directory.
  3) C-c C-e (org-export-dispatch) and type ``P'' ``x'' ``octopress''
  4) In command line terminal:
     : rake preview
     (see [[http://octopress.org/docs/][Octopress Documentation - Octopress]] for details)
  5) Check your article in browser.

* Contact Info
  The updated version might be available from:
  http://github.com/yoshinari-nomura/org-octopress
